### ISSUE TITLE
Travis failed at uploading ppc64le for master

### ISSUE THREAD

**Issue by leofang** [conda-forge/spdlog-feedstock#38]
c96430f in the master failed -- @conda-forge/core or @conda-forge/spdlog Can someone rerun the CI? Thanks!

**Comment by dopplershift** [comment]
I'm not able to restart it for whatever reason. You can also do `git commit --allow-empty -m 'Re-run CI'` and `git push`.

**Comment by leofang** [comment]
@dopplershift Unfortunately I am not a maintainer...

**Comment by leofang** [comment]
Matt from the core team restarted the CI and a package is uploaded. Closing as resolved.
